export class ResepArray {
    constructor ( 
        public id:Number, 
        public id_customer:Number,
        public r_sph:Number, 
        public l_sph:Number, 
        public r_cyl:Number, 
        public l_cyl:Number, 
        public r_axs:Number, 
        public l_axs:Number,
        public r_add:Number, 
        public l_add:Number, 
        public pd:Number, 
        public visakhir:Number, 
        public A:Number, 
        public B:Number,
        public dbl:Number, 
        public mpd:Number,
        public shpv:Number,
        public jenisframe:String,
        public koridor:String,
        public visusbalance:String,
        public dukeelder:String,
        public wrapangle:String,
        public pantoskopik:String,
        public vertexdistance:String,
        public catatan:String,
    ){}
}